### ISSUE TITLE
Startup error: Exception when downloading translations

### ISSUE THREAD

**Issue by MightyKnight** [gbl/Beenfo#14]
The following error is always printed in the log file when starting the game.
I tested it in isolation, eventually coming to only Beenfo with Fabric API being the cause.

I can't provide further information, this just happens every time on startup.

**Beenfo:** `beenfo-1.16.4-fabric0.25.1-1.3`
**Fabric API**: `fabric-api-0.30.0+1.16`

### [log_error_translations.txt](https://github.com/gbl/Beenfo/files/5898475/log_error_translations.txt)

```
[19:17:58] [main/INFO]: [Indigo] Registering Indigo renderer!
[19:17:59] [main/INFO]: Backend library: LWJGL version 3.2.2 build 10
[19:18:00] [Thread-52/INFO]: [STDERR]: Exception when downloading translations
[19:18:00] [Thread-52/INFO]: [STDERR]: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1497)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:563)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2661)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2583)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1769)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at java.net.URL.openStream(URL.java:1038)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at de.guntram.mcmod.crowdintranslate.CrowdinTranslate.getCrowdinTranslations(CrowdinTranslate.java:155)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at de.guntram.mcmod.crowdintranslate.CrowdinTranslate.run(CrowdinTranslate.java:124)
[19:18:00] [Thread-52/INFO]: [STDERR]: Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at sun.security.validator.Validator.validate(Validator.java:260)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1479)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	... 17 more
[19:18:00] [Thread-52/INFO]: [STDERR]: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
[19:18:00] [Thread-52/INFO]: [STDERR]: 	... 23 more
[19:18:05] [main/INFO]: Narrator library for x64 successfully loaded
[19:18:05] [main/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Renderer API (v1), Fabric Key Bindings (v0), GBfabrictools, Fabric Loader, Beenfo, Fabric Structure API (v1), Fabric Containers (v0), Fabric Object Builder API (v1), Fabric Game Rule API (v1), Fabric API Base, Fabric Rendering Data Attachment (v1), Fabric Textures (v0), Fabric Rendering Fluids (v1), Fabric BlockRenderLayer Registration (v1), Fabric Lifecycle Events (v1), Fabric Renderer Registries (v1), Fabric Loot Tables (v1), Fabric API, Fabric Particles (v1), Fabric Networking (v0), Fabric Networking Block Entity (v0), Fabric Screen Handler API (v1), Fabric Command API (v1), Fabric Screen API (v1), Fabric Tool Attribute API (v1), Fabric Renderer - Indigo, Fabric Events Interaction (v0), Fabric Item API (v1), Fabric Crash Report Info (v1), Fabric Entity Events (v1), Fabric Rendering (v0), Fabric Key Binding API (v1), Fabric Rendering (v1), Fabric Resource Loader (v0), Fabric Content Registries (v0), Fabric Tag Extensions (v0), Fabric Biome API (v1), Fabric Commands (v0), Fabric Registry Sync (v0), Fabric Mining Levels (v0), Fabric Networking API (v1), Fabric Events Lifecycle (v0), Fabric Item Groups (v0), Fabric Models (v0), Fabric Object Builders (v0))
[19:18:05] [main/INFO]: [STDOUT]: Inject generated resource packs.

```

**Comment by gbl** [comment]
That's the old version of Java that Minecraft used, together with the online translation download that Beenfo has. The only negative effect is you won't get updated translation if they are made after you install the mod. With MC 1.17 and its Java 16, the problem should be gone anyway.
