### ISSUE TITLE
Crash when loading the game

### ISSUE THREAD

**Issue by bilintsui** [gbl/Beenfo#22]
When I loading Minecraft 1.18.2 with Beenfo v1.3.3, the game crashed.
Maybe this issue is caused by an incompatible Minecraft version? (v1.3.3 is for Minecraft 1.18.1)

**Environment:**
- Windows 10.0.19044.1566 x64
- OpenJDK 17.0.1 x64
- Fabric Loader 0.13.3

**Other installed mods:**
- Fabric API 0.47.8
- Mod Menu 3.1.0

Crash report: [crash-2022-03-02_23.30.14-client.txt](https://github.com/gbl/Beenfo/files/8170927/crash-2022-03-02_23.30.14-client.txt)
Game log: [latest.log](https://github.com/gbl/Beenfo/files/8170931/latest.log)

**Comment by Svish** [comment]
Same here, Beenfo 1.18.1-fabric0.25.0-1.3.3 causes 1.18.2 client to crash on startup with this error:

```
[16:33:55] [Render thread/ERROR]: Mixin apply for mod crowdin-translate failed mixins.crowdintranslate.json:ReloadableResourceManagerImplMixin -> net.minecraft.class_3304: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method method_14475 in mixins.crowdintranslate.json:ReloadableResourceManagerImplMixin was not located in the target class net.minecraft.class_3304. Using refmap crowdin-translate-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method method_14475 in mixins.crowdintranslate.json:ReloadableResourceManagerImplMixin was not located in the target class net.minecraft.class_3304. Using refmap crowdin-translate-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:436) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:412) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:340) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:299) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.11.2+mixin.0.8.5.jar:0.11.2+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) [fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
	at net.minecraft.class_310.<init>(class_310.java:504) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:197) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```
Other mods installed, if that makes a difference:

![image](https://user-images.githubusercontent.com/142162/156930251-4834f004-4815-414c-91fc-0a7ff4d16674.png)

**Comment by mkikets99** [comment]
Hmm... i have same issue...

@gbl
A quick note for what is a problem:
1. `Beenfo` not compatible with `1.18.2`
2. Issue from logs shows that it is an error with `crowdin-translate` section

**Comment by gbl** [comment]
Updated version for 1.18.2 pushed to CF and Modrinth.

**Comment by p3lim** [comment]
@gbl Could you the same for Forge 1.18.2 too? :)

**Comment by gbl** [comment]
The Forge version shouldn't have the problem as it doesn't use CrowdinTranslate.

**Comment by p3lim** [comment]
Would still appreciate a 1.18.2 forge release, makes it easier with launchers, and it seems like the work required is minimal.
